blocklist_keywords: []
min_title_length: 1
max_items: 500     # keep history lightweight on Pages

pin:
  - title: "Weekly Economist Espresso (manual pick)"
    url: "https://example.com/espresso"
    note: "Always worth a glance."
